//register works
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "email": "gio1234@gmail.com",
    "password": "shara123",
    "name": "Giorgi Sharashenidze"
}
###
//login works
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "gio1234@gmail.com",
    "password": "shara123"
}
###
//user works
GET http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTYyNWQ2M2Y0OGVjMTJhNTYzOWQ2NyIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA0NTI4MjJ9.6z-lZ0pQvwF9Txv_FGN6RzMmKI6i2LX57MLDHE1tImE
