//register works
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "email": "gio1234@gmail.com",
    "password": "shara123",
    "name": "Giorgi Sharashenidze"
}
###
//login works
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "gio1234@gmail.com",
    "password": "shara123"
}
###
//Done
GET http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo

###
//Done
POST http://localhost:3000/workout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo
Content-Type: application/json

###
//Done
GET http://localhost:3000/workouts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo

###
//Done
PATCH http://localhost:3000/workout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo
Content-Type: application/json

{
    "workoutName": "Yes",
    "workoutDescription":  "Yes",
    "workoutId": "6098b906203e3621e565cf3f"
}

###
//Done
GET http://localhost:3000/circuits HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo
Content-Type: application/json

{
    "circuitIds": [
        "6098b906203e3621e565cf3e"
    ]
}

###
//
PATCH http://localhost:3000/circuits HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTdjMWY4ZmZiY2FkMGE3YjU5OTVhYSIsImVtYWlsIjoiZ2lvMTIzNEBnbWFpbC5jb20iLCJpYXQiOjE2MjA1NTgzMjh9.GOr38qEWAaiOKFHkZz_8DXcEKLnm4TttM4gvzCVpSdo
Content-Type: application/json

{
    "bulkWrites": [
       { "insertOne":

            {
               "document" :
                {   
                    "circuitIds": [
                        "6097c4b5c845650c03f66169"
                    ],
                    "_id": "6097c4b5c845650c03f6616a",
                    "description": "New description",
                    "exerciseTotalAmount": 0,
                    "setTotalAmount": 0,
                    "name": "Workout 2",
                },
            }
        },
        { "updateOne":
            {
               "filter" : { "_id" : "" },
               "update" : { "$set" : { "status" : "Critical Injury" } }
            }
        },
         
    ],
    "circuitIds": []
}

